name: Control Instance from Workflow

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: number
      command_name:
        description:
          "Name of the command to execute: create, delete, shelve, unshelve"
        required: true
        type: string
      unapprove_after_delete:
        description: "Whether to unapprove after deleting the instance"
        type: boolean
        default: false
  workflow_call:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: string
      command_name:
        description:
          "Name of the command to execute: create, delete, shelve, unshelve"
        required: true
        type: string
      unapprove_after_delete:
        description: "Whether to unapprove after deleting the instance"
        type: boolean
        default: false
permissions:
  issues: write
  checks: read

jobs:
  control:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: Control instance
        uses: ./.github/actions/control-instance
        with:
          os_cloud: ${{ vars.MORPHOCLOUD_OS_CLOUD }}
          issue_number: ${{ inputs.issue_number }}
          command_name: ${{ inputs.command_name }}
          unapprove_after_delete: ${{ inputs.unapprove_after_delete }}
          instance_name_prefix: ${{ vars.INSTANCE_NAME_PREFIX }}
          token: ${{ secrets.GITHUB_TOKEN }}
          string_encryption_key: ${{ secrets.STRING_ENCRYPTION_KEY }}
          mail_server_username: ${{secrets.MAIL_USERNAME}}
          mail_server_password: ${{secrets.MAIL_PASSWORD}}
