name: Delete Volume

on:
  issue_comment:
    types: [created]

jobs:
  delete_volume:
    runs-on: self-hosted
    if:
      ${{ !github.event.issue.pull_request &&
      contains(github.event.issue.labels.*.name, 'request-type:instance') && (
      contains(github.event.comment.body, '/delete_volume') ) }}
    steps:
      - name: delete_volume command
        id: delete_volume_command
        uses: github/command@v2.0.2
        with:
          command: "/delete_volume"
          reaction: "rocket"
          allowed_contexts: "issue"
          permissions: "read,triage,write,maintain,admin"
          allowlist:
            "${{ vars.MORPHOCLOUD_GITHUB_ADMINS }},${{
            github.event.issue.user.login }}"

      - uses: actions/checkout@v6

      - name: Delete volume
        id: delete_volume
        if: ${{ steps.delete_volume_command.outputs.continue == 'true' }}
        uses: ./.github/actions/delete-volume
        with:
          os_cloud: ${{ vars.MORPHOCLOUD_OS_CLOUD }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          instance_name_prefix: ${{ vars.INSTANCE_NAME_PREFIX }}
          volume_name_suffix: ${{ vars.VOLUME_NAME_SUFFIX }}
