name: "Instance Request Initial Comments"
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
  workflow_call:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: string

jobs:
  initial_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Inputs
        id: collect_inputs
        shell: bash
        run: |
          echo "EVENT_NAME [$EVENT_NAME]"
          if [[ "$EVENT_NAME" == "issues" ]]; then
            issue_number=${{ github.event.issue.number || inputs.issue_number }}
          elif [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then
            issue_number=${{ github.event.inputs.issue_number }}
          else
            echo "::error ::Unsupported EVENT_NAME [$EVENT_NAME]"
            exit 1
          fi
          if [[ -z "$issue_number" || "$issue_number" == "null" ]]; then
            echo "::error ::issue_number not provided"
            exit 1
          fi
          echo "issue_number=$issue_number" >> $GITHUB_OUTPUT
        env:
          EVENT_NAME: ${{ github.event_name }}

      - uses: actions/checkout@v6

      - name: Define instance name
        id: define
        uses: ./.github/actions/define-instance-name
        with:
          prefix: ${{ vars.INSTANCE_NAME_PREFIX }}
          issue_number: ${{ steps.collect_inputs.outputs.issue_number }}

      - name: description (instance name)
        uses: julien-deramond/update-issue-body@v1.1.0
        with:
          issue-number: ${{ steps.collect_inputs.outputs.issue_number }}
          body: |
            ### Instance Name

            `${{ steps.define.outputs.instance_name }}`

            _The instance name is derived from the GitHub issue number using the template `${{ steps.define.outputs.instance_prefix }}instance-NNN`. The instance may also be located in the exosphere interface using this name._
          edit-mode: append
          append-separator: newline

      - name: Define volume name
        id: define_volume_name
        uses: ./.github/actions/define-volume-name
        with:
          issue_number: ${{ steps.collect_inputs.outputs.issue_number }}
          suffix: ${{ vars.VOLUME_NAME_SUFFIX }}

      - name: description (volume name)
        uses: julien-deramond/update-issue-body@v1.1.0
        with:
          issue-number: ${{ steps.collect_inputs.outputs.issue_number }}
          body: |
            ### Volume Name

            `${{ steps.define_volume_name.outputs.volume_name }}`

            _The volume name is derived from the GitHub issue number using the template `My-Data-NNN${{ steps.define_volume_name.outputs.volume_suffix }}`. The volume may also be located in the exosphere interface using this name._
          edit-mode: append
          append-separator: newline

      - name: Find Issue Commands Comment
        uses: peter-evans/find-comment@v4
        id: fc_commands
        with:
          issue-number: ${{ steps.collect_inputs.outputs.issue_number }}
          comment-author: "github-actions[bot]"
          body-includes: "### Supported Issue Commands"

      - name: comment (issue commands)
        uses: peter-evans/create-or-update-comment@v5.0.0
        with:
          comment-id: ${{ steps.fc_commands.outputs.comment-id }}
          issue-number: ${{ steps.collect_inputs.outputs.issue_number }}
          body-path: "issue-commands.md"
          edit-mode: replace
